#!/usr/bin/env node
// Turns a recording made by the Click Timing Recorder extension into a Puppeteer script.
//
//   node convert.mjs [recording.json] [replay.mjs]
//
// Then:  npm i puppeteer   and   node replay.mjs      (SPEED=2 node replay.mjs = twice as fast)

import fs from 'fs';

const [, , inFile = 'recording.json', outFile = 'replay.mjs'] = process.argv;
const events = JSON.parse(fs.readFileSync(inFile, 'utf8'));

const ACTIONS = new Set(['click', 'fill', 'select', 'key']);
const isAction = (e) => ACTIONS.has(e.type);

// Does a full page load happen after events[i] and before the next action?
function causesNavigation(i) {
  for (let j = i + 1; j < events.length; j++) {
    if (events[j].type === 'navigate') return true;
    if (isAction(events[j])) return false;
  }
  return false;
}

const body = [];
const add = (line) => body.push('  ' + line);
const str = JSON.stringify;

let base = null;             // moment the next pause is measured from
let started = false;         // has the first page.goto been emitted?
let actionSinceLoad = true;  // was there an action since the last page load?
let navExpected = false;     // an earlier action already waits for the next page load

function pause(t) {
  const ms = base == null ? 0 : Math.max(0, Math.round(t - base));
  if (ms >= 50) add(`await sleep(${ms});`);
}

events.forEach((e, i) => {
  if (e.type === 'navigate') {
    if (!started) {
      add(`await page.goto(${str(e.url)}, { waitUntil: 'load' });`);
      started = true;
    } else if (actionSinceLoad && !navExpected) {
      // Page loaded without any click causing it: typed URL or reload
      pause(e.t);
      add(`// page loaded without a click (typed URL or reload)`);
      add(`await page.goto(${str(e.url)}, { waitUntil: 'load' });`);
    }
    navExpected = false;
    base = e.t;
    actionSinceLoad = false;
    return;
  }

  if (e.type === 'loaded') {
    if (!actionSinceLoad) base = e.t; // think-time is measured from when the page finished loading
    return;
  }

  if (!isAction(e)) return;

  pause(e.t);
  const nav = causesNavigation(i);
  const navOpt = nav ? ', { nav: true }' : '';
  const sel = str(e.selectors || []);
  if (e.text) add(`// ${e.type}: ${e.text}`);

  switch (e.type) {
    case 'click':
      add(`await click(page, ${sel}${navOpt});`);
      break;
    case 'fill': {
      const value = e.value === '__PASSWORD__' ? 'process.env.PASSWORD' : str(e.value);
      const len = String(e.value).length;
      // real password length is unknown (it is never recorded), so use a typical typing speed
      const perChar = e.value === '__PASSWORD__' ? 80 : len > 1 ? Math.min(400, Math.round((e.durationMs || 0) / (len - 1))) : 0;
      add(`await fill(page, ${sel}, ${value}, ${perChar});`);
      break;
    }
    case 'select':
      add(`await selectOption(page, ${sel}, ${str(e.value)});`);
      break;
    case 'key':
      add(`await pressKey(page, ${str(e.key)}${navOpt});`);
      break;
  }

  base = e.t + (e.durationMs || 0);
  actionSinceLoad = true;
  if (nav) navExpected = true;
});

const script = `// Generated by convert.mjs from ${inFile}
// Run:  node ${outFile}      (SPEED=2 node ${outFile}  replays twice as fast)
import puppeteer from 'puppeteer';

const SPEED = Number(process.env.SPEED) || 1;
const sleep = (ms) => new Promise((r) => setTimeout(r, ms / SPEED));

// Try each recorded selector in order until one matches.
async function find(page, selectors, timeout = 5000) {
  for (const sel of selectors) {
    try {
      const el = await page.waitForSelector(sel, { visible: true, timeout });
      if (el) return el;
    } catch {}
  }
  throw new Error('Element not found: ' + selectors.join('  |  '));
}

async function click(page, selectors, { nav = false } = {}) {
  const el = await find(page, selectors);
  if (nav) {
    await Promise.all([page.waitForNavigation({ waitUntil: 'load', timeout: 30000 }), el.click()]);
  } else {
    await el.click();
  }
}

async function fill(page, selectors, value, perCharDelay) {
  const el = await find(page, selectors);
  await el.focus();
  await el.evaluate((e) => { try { e.select(); } catch {} }); // select existing text so typing replaces it
  if (value === '') await page.keyboard.press('Backspace');
  else await el.type(value, { delay: perCharDelay / SPEED });
}

async function selectOption(page, selectors, value) {
  const el = await find(page, selectors);
  await el.select(value);
}

async function pressKey(page, key, { nav = false } = {}) {
  if (nav) {
    await Promise.all([page.waitForNavigation({ waitUntil: 'load', timeout: 30000 }), page.keyboard.press(key)]);
  } else {
    await page.keyboard.press(key);
  }
}

const browser = await puppeteer.launch({ headless: false, defaultViewport: null });
try {
  const page = await browser.newPage();
${body.join('\n')}
  await sleep(1000);
} finally {
  await browser.close();
}
`;

fs.writeFileSync(outFile, script);
console.log(`Wrote ${outFile} (${body.length} lines of steps)`);
